spring:
  application:
    name: documents

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    charset: UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true